#Exercises

**Question 1:** A researcher performs an experiment where they extract 3 measurements for every user. When analyzing the data, the researcher found out that the measurements for the 3rd, 8th and 9th users were off by 50. Using indexing, update the values.

In [8]:
import numpy as np
measurements = np.array([[2100, 2416, 1740],
                        [2535, 1710, 1875],
                        [2148, 2127, 2453],
                        [2829, 1649, 1736],
                        [2208, 2035, 1733],
                        [2228, 1914, 2385],
                        [1946, 1935, 2112],
                        [2965, 2120, 2471],
                        [1550, 1984, 2706],
                        [2846, 2546, 2246],
                        [2285, 1752, 2242],
                        [1800, 2799, 2052],
                        [2576, 1560, 2239],
                        [2752, 1596, 2582],
                        [2134, 2615, 2097]])

#answer here
measurements[2] += 50
measurements[7] -= 50
measurements[8] += 50
print(measurements[2], measurements[7], measurements[8])

[2198 2177 2503] [2915 2070 2421] [1600 2034 2756]


**Question 2:** Given the 2D matrix ``A``, calculate the average of numbers that are divisible by 3.

In [9]:
A = np.array([[ 45, 184, 266, 267, 234],
              [ 69,  74, 141, 120, 132],
              [116, 138, 245,  16,  32],
              [ 98, 243,  96, 193, 132],
              [ 53, 206, 236,  50, 171]])

#answer here
# Calculate average of numbers divisible by 3
print(np.mean(A[A % 3 == 0]))

149.0


**Question 3:** Using NumPy's `.where()` function, square all values larger than the mean of the matrix.

In [10]:
A = np.array([[ 67,  21, 178,  58,  73],
              [ 33, 128, 276, 114,  66],
              [145, 132,  99, 218, 248],
              [253,  83, 241, 150,  27],
              [164, 259, 104,  31, 137]])

#answer here
# Using Numpy's where function, square all values larger than the mean of the matrix
print(np.where(A > np.mean(A), A**2, A))

[[   67    21 31684    58    73]
 [   33   128 76176   114    66]
 [21025   132    99 47524 61504]
 [64009    83 58081 22500    27]
 [26896 67081   104    31 18769]]


**Question 4:** Given the 3D matrix ``A``, slice the matrix into a sub-matrix that extracts the 3rd dimension 2D array, and from that extracts its 3rd to 10th (inclusive) rows, and up to the third to last columns (inclusive).

Multiply each number in the resulting slice matrix by 3, and return the median value.

*Hint*: to get a better understanding of which dimension is width, height, and depth, check the `.shape` of the matrix.

In [33]:
A = np.array([[[66, 48, 90, 88, 81, 88],
              [75, 91, 86, 51, 56, 98],
              [41, 71, 35, 28, 89, 60],
              [ 3, 17, 20, 90, 15, 37],
              [87, 47, 79, 97, 95, 69],
              [85, 51, 18, 41, 69, 73],
              [36, 55, 91, 27, 48, 67],
              [55, 98, 80, 74, 77, 21],
              [68, 12, 26, 67, 45, 21],
              [26, 20, 35, 13,  9, 42]],

             [[34, 54, 94,  8, 83, 23],
              [82, 44, 75, 24, 27, 41],
              [13, 60, 91, 20, 86, 89],
              [43, 14, 69, 32, 10, 10],
              [82, 41,  2, 55, 92, 16],
              [96, 67, 11, 53, 64, 33],
              [26, 10, 18, 59, 72, 81],
              [31, 49, 35, 71, 75, 34],
              [39,  1, 62, 28, 58,  6],
              [49, 47,  5, 74, 85, 71]],

             [[89, 22, 28, 26, 70, 27],
              [86,  2, 45, 51, 32, 39],
              [41, 60, 77, 53, 32, 28],
              [92, 27, 49, 88, 72, 41],
              [58, 59, 87,  1, 86, 55],
              [ 4, 15, 86, 14, 22, 31],
              [43, 29, 23, 42, 30,  5],
              [25, 18, 84, 79, 38, 45],
              [32,  9, 13, 41, 34, 28],
              [11, 67,  9, 62, 79, 43]]])

#answer here
# A.shape
# Taking the 3rd dimension 2D array (assuming index starts from 0, it would be A[2, :, :])
# Extracting the 3rd to 10th rows (inclusive) and up to the third to last column (inclusive)
sub_matrix = A[2, 2:11, :-2]

# Multiply each number in the resulting sub-matrix by 3
sub_matrix *= 3

# Print the median of the resulting sub-matrix
print(np.median(sub_matrix))


124.5


**Question 5:** Using ``np.tile()``, construct the following matrix:

$A = \begin{matrix}
10 & 9 & 10 &  9 & 10 & 9 \\
8 & 7 & 8 & 7 & 8 & 7 \\
10 & 9 & 10 &  9 & 10 & 9 \\
8 & 7 & 8 & 7 & 8 & 7 \\
10 & 9 & 10 &  9 & 10 & 9 \\
8 & 7 & 8 & 7 & 8 & 7 \\
10 & 9 & 10 &  9 & 10 & 9 \\
8 & 7 & 8 & 7 & 8 & 7 \\
\end{matrix}$


In [23]:
#answer here
temp = np.array([[10, 9], [8, 7]])
repetitions = (4, 3) # Repeat 4 times along axis 0 and 3 times along axis 1
np.tile(temp, repetitions)

array([[10,  9, 10,  9, 10,  9],
       [ 8,  7,  8,  7,  8,  7],
       [10,  9, 10,  9, 10,  9],
       [ 8,  7,  8,  7,  8,  7],
       [10,  9, 10,  9, 10,  9],
       [ 8,  7,  8,  7,  8,  7],
       [10,  9, 10,  9, 10,  9],
       [ 8,  7,  8,  7,  8,  7]])

**Question 6:** Create a 1D array with 120 equally spaced numbers between 1 and 1000 inclusive. Convert it to a ``12x10`` matrix, and calculate the average of every other row rounded to the nearest hunderedths (i.e. 2 decimal points).

For every row print an output statement in the following format:

```
The average for row  0 is 38.78
The average for row  2 is 206.68
...
```

*Hint:* look up ``np.linspace()``

In [26]:
#answer here
# Create a 1D array with 120 equally spaced numbers between 1 and 1000
arr = np.linspace(1, 1000, 120)

# Reshape it into a 12x10 matrix
matrix = arr.reshape(12, 10)

# Calculate and print the average for every other row
for i in range(0, matrix.shape[0], 2):
    avg = np.mean(matrix[i, :])
    # Using Pyhton's string formatting, print the average with 2 decimal places
    print(f"The average for row {i} is {avg:.2f}")


The average for row 0 is 38.78
The average for row 2 is 206.68
The average for row 4 is 374.58
The average for row 6 is 542.47
The average for row 8 is 710.37
The average for row 10 is 878.27
