-----
# Numerical Python (NumPy) - Part 1: Exercises
-----

In [50]:
import numpy as np

**Question 1:**

With numpy you could easily convert a number of farenheit values to ceclius.

Create an array of typical farenheit values in winter
`[0,-10,-5,-15,0]` and convert all values to celcius using the following formula for conversion: ((°F − 32) × 5/9 = °C)

In [51]:
#answer here
farenheit_vals = np.array([0, -10, -5, -15, -40])
# Convert to celsius
# To improve result readability, round to 2 decimal places
celsius_vals = np.round((farenheit_vals - 32) * (5/9), 2)
celsius_vals


array([-17.78, -23.33, -20.56, -26.11, -40.  ])

**Question 2:** Create an array of length 100 with random integers from 1 to 9999. Double all its values, then convert it to a square matrix.

Challenge: Can you do it all in one line of code?

In [52]:
#answer here
# Create an array of length 100 filled with random integers from 1 to 9999
# Multiply each value by 2
# Reshape the array to be 10x10 matrix
rand_arr = (np.random.randint(1, 9999, 100) * 2).reshape(10, 10)
rand_arr

array([[18968,   598,  3304, 14072,  6324, 16266, 12936,  9818,  5456,
         7550],
       [15728, 10340, 12516, 11850, 13912, 16414,  6010,  9542, 10336,
        19316],
       [ 8664,  9408, 11604, 19806,  9982, 13740, 11134,  5150, 15018,
        14870],
       [ 9638,   162, 18900, 10986, 16908, 10978,  1526,  7076,  3576,
        19950],
       [18770, 13270,   884,  3996,  4926,  3296,  9096,  1542, 14384,
         7720],
       [12816,  1188, 13020, 13542, 19382, 15862, 19456, 10566, 12820,
        14008],
       [ 1882, 12474, 19592, 13944,  2262, 18768,  8208, 12074,  7724,
        10720],
       [ 2774,  8036, 10204, 11988,  6820,  8512,  4212,  8714,  9152,
         8230],
       [ 3628,  8582, 15484, 12378, 16238,  4346, 13658, 15656,   566,
        10566],
       [ 5618,  3696,  8300, 12382, 11860,  5352, 13736, 15330, 18972,
        14118]])

**Question 3:** Given matrices `A` and `B`, calculate the average of all the number in both the matrices.

In [53]:
import numpy as np
A = np.array([[ -8,  99,  -71,  78,  22,  54,  22,  51,   8,  61],
              [ 24,  44,  97, 102,  35, 115,  93,   9, 112, 129],
              [ 67,  64,  69,   4,  73,  58,  34,  44,  11, 142],
              [ 32, 128, 141,   8, 114,  64,   6,  74, 111,  20],
              [ 85, 145,  14,  92,   4,  -1,  52,  11,  24,  45],
              [  5, 125,  76,  55,  -2,  82, 123, 127,  58, 103],
              [ 87, 143,  39,  38, 108,  55,  57, 145, 146,  52],
              [135,  52, 129,  -6,  38, 101, 121,  62,  65,   8],
              [127,  47,   4,   0,  67, 128,  -7, 126,  88,  95],
              [135, 139,  82,  70,  57,  79, 138,  63,  72, 119]])

B = np.array([[ 58,  92, 101, 104,  31,  -4,  91, 145, 114,  38],
              [ 96,  53,  60,  45,  46, 145,  70, -10,  34,  86],
              [  7, 118,  17, 140, 118, 129,  -8,   3,  95,   0],
              [ 53, 135, 114,  63,  25,  24,   3, 124,  10, 139],
              [ 88,  -5,  47, 126,  32,  70, 115,  74,  35,   2],
              [ 28,  80,  21,  92, 137,  17,   6,  88, 104, 131],
              [ 27, 142,  -6,  96,  66,  59,   7, 108, 139,  96],
              [ 82, 115, 123, 108,   7,  93, 147,  -1,  66,  98],
              [135, 147, 117,  65, 130, 118,  30,  50, 114,  83],
              [ 22,  36, 118,  -7,  -6, -10,  -2,  94,  14, 110],
              [ 14,  79, 142, 108, 115,  63,  84, 104, 136,  47]])

#answer here
# Calculate average of all numbers in both matrices
np.mean(np.concatenate((A, B)))

69.43333333333334

**Question 4:** Consider an array `A`, normalize the values so that the values are between 0 and 1. As a reminder, the formula for normalization is:

$X_{normalized} = \frac{X - X_{min}}{X_{max}-X_{min}}$

In [54]:
A = np.array([[731, 160, 852, 390, 312, 871, 274, 640, 336, 911],
              [408, 529, 432, 269, 801, 683, 663, 257, 938, 646],
              [236, 500, 762, 285, 445, 779, 932, 857, 602, 196],
              [609, 706, 768, 770, 626, 740, 224, 867, 877, 469],
              [749, 382, 657, 998, 687, 708, 479, 274, 449, 927],
              [499, 273, 377, 950, 382, 210, 828, 972, 981, 928],
              [136, 868, 744, 594, 511, 734, 844, 530, 445, 208],
              [560, 697, 978, 995, 499, 250, 826, 331, 892, 276],
              [753, 578, 981, 483, 872, 543, 138, 816, 111, 427],
              [501, 766, 997, 598, 140, 143, 682, 334, 569, 119],
              [255, 915, 941, 797, 427, 227, 778, 887, 824, 613],
              [959, 704, 142, 988, 229, 907, 713, 430, 766, 174],
              [166, 176, 430, 100, 627, 462, 571, 488, 711, 403],
              [460, 939, 417, 131, 480, 658, 735, 802, 496, 889],
              [118, 337, 453, 163, 806, 614, 619, 777, 626, 706],
              [813, 586, 925, 823, 459, 281, 974, 973, 255, 336],
              [625, 236, 539, 227, 275, 528, 761, 754, 291, 676],
              [242, 272, 398, 426, 612, 847, 930, 764, 360, 225],
              [919, 403, 223, 169, 370, 967, 169, 400, 205, 758],
              [955, 898, 653, 999, 278, 391, 230, 798, 821, 565]])

#answer here
# Normalize all values in matrix A to be between 0 and 1
A = (A - np.min(A)) / (np.max(A) - np.min(A))
A

array([[0.70189099, 0.06674082, 0.83648498, 0.32258065, 0.23581758,
        0.85761958, 0.19354839, 0.60066741, 0.2625139 , 0.90211346],
       [0.34260289, 0.47719689, 0.36929922, 0.18798665, 0.77975528,
        0.64849833, 0.62625139, 0.17463849, 0.93214683, 0.60734149],
       [0.1512792 , 0.44493882, 0.73637375, 0.2057842 , 0.38375973,
        0.75528365, 0.92547275, 0.84204672, 0.55839822, 0.10678532],
       [0.56618465, 0.67408231, 0.74304783, 0.74527253, 0.58509455,
        0.71190211, 0.13793103, 0.85317019, 0.86429366, 0.41045606],
       [0.72191324, 0.31368187, 0.61957731, 0.99888765, 0.65294772,
        0.67630701, 0.42157953, 0.19354839, 0.38820912, 0.91991101],
       [0.44382647, 0.19243604, 0.30812013, 0.94549499, 0.31368187,
        0.12235818, 0.80978865, 0.96996663, 0.97997775, 0.92102336],
       [0.04004449, 0.85428254, 0.7163515 , 0.54949944, 0.45717464,
        0.70522803, 0.82758621, 0.47830923, 0.38375973, 0.12013348],
       [0.51167964, 0.66407119, 0.9766407

**Question 5:** Generate an array that contains all consecutive odd numbers between 0 to 16. Convert this array to a 3-D array with equal sides.

Food for thought: Can someone tell me when is it better to use `.reshape()` vs `.resize()`?

In [55]:
#answer here
# Generate odd numbers array and reshape to be 2x2x2 (Three-Dimensional Matrix)
odd_nums = np.arange(1, 16, 2).reshape(2, 2, 2)
odd_nums

array([[[ 1,  3],
        [ 5,  7]],

       [[ 9, 11],
        [13, 15]]])

**Question 6:** Another useful and important elementwise manipulation that we will explore more in the next lecture is the boolean array. We can apply a boolean operator or expression on any array and a boolean value will be returned for every element in the original matrix; i.e. with True being emitted if it meets the condition and False oetherwise.

For instance, if we want to get a boolean array to check which values in matrix A have values that are greater than 20, we can do `A > 20`

$A = \begin{pmatrix}
  14 & 45 & 63 \\
  25 & 23 & 10 \\
  38 & 15 & 13
 \end{pmatrix}$

$A>20 = \begin{pmatrix}
  False & True & True \\
  True & True & False \\
  True & False & False
 \end{pmatrix}$

As an exercise, create matrix `A` and generate a boolean matrix that returns `True` if a number is a multiple of 5, and `False` otherwise.

In [56]:
import numpy as np

# answer here
# Create the given 3 * 3 matrix
A = np.array([[14,  45,  63],
              [25, 23, 10],
              [38, 15, 13]])
A = A % 5 == 0  # Check if A is a multiple of 5 or not
A


array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])